### ISSUE TITLE
Malformed packet errors on websocket listener

### ISSUE THREAD

**Issue by tommyminds** [mochi-co/mqtt#115]
Hi,

When publishing packages to the websocket listener using the Paho MQTT client library (both 3.11 and 5), I am getting many malformed packet errors. If I switch from ws to tcp listener, I am not getting these errors with the exact same client code.

<img width="1194" alt="Screenshot 2022-12-13 at 16 53 11" src="https://user-images.githubusercontent.com/123474/207380773-6bce7c38-1709-4fe3-abac-cadf7ed88611.png">

Any idea what the issue could be here?

**Comment by mochi-co** [comment]
Thanks @tommyminds! I vaguely remember reading about a change in the accepted websocket protocol names, I look into it and see if i can replicate the issue!

**Comment by tommyminds** [comment]
Unrelated, but it also seems the websocket library used by mochi has been put in archive mode. 

[https://github.com/gorilla/websocket](url)

Guess not really important right now, but might at some point also be worth looking to alternatives

**Comment by mochi-co** [comment]
@tommyminds I haven't been able to replicate this with EMQX, would you be able to share a code sample? Thank you!

**Comment by tommyminds** [comment]
I trimmed down the client code as much as I could to hopefully create something reproducable. I am running both code snippets against a local docker container running mochi-co. Not that I am not spreading out the message publishes (on purpose)

### Using the paho.golang (MQTT v5) client

```golang
package main

import (
	"context"
	"log"
	"net/url"
	"time"

	"github.com/eclipse/paho.golang/autopaho"
	"github.com/eclipse/paho.golang/paho"
)

func main() {
	ctx := context.Background()
	endpoint, _ := url.Parse("ws://localhost:1882/mqtt")

	client, err := autopaho.NewConnection(ctx, autopaho.ClientConfig{
		BrokerUrls: []*url.URL{endpoint},
		ClientConfig: paho.ClientConfig{
			ClientID: "test",
			OnClientError: func(err error) {
				log.Printf("server disconnected: %v", err)
			},
			OnServerDisconnect: func(d *paho.Disconnect) {
				log.Println("server disconnected")
			},
		},
		OnConnectError: func(err error) {
			log.Printf("connection error: %v", err)
		},
	})
	if err != nil {
		log.Fatalln(err)
	}

	defer client.Disconnect(ctx)

	publishTicker := time.NewTicker(1 * time.Second)
	defer publishTicker.Stop()

	for {
		<-publishTicker.C
		for i := 0; i < 100; i++ {
			_, err := client.Publish(ctx, &paho.Publish{
				Topic:   "test",
				QoS:     0,
				Payload: []byte("test"),
			})

			if err != nil {
				log.Fatalln(err)
			}
		}
		log.Println("published 100 messages")
	}
}
```
<img width="1219" alt="Screenshot 2022-12-13 at 18 57 49" src="https://user-images.githubusercontent.com/123474/207409274-f9ec3427-c394-4da6-a1ca-f138b9316911.png">

### Using the paho.mqtt.golang (MQTT 3.11) client. 
Note I had to set the batch size higher for the error to show up

```golang
package main

import (
	"log"
	"time"

	mqtt "github.com/eclipse/paho.mqtt.golang"
)

func main() {
	opts := mqtt.NewClientOptions()

	opts.AddBroker("ws://localhost:1882/mqtt")
	opts.SetClientID("test")
	opts.OnConnectionLost = func(cl mqtt.Client, err error) {
		log.Printf("connection lost: %v", err)
	}

	client := mqtt.NewClient(opts)
	if token := client.Connect(); token.Wait() && token.Error() != nil {
		log.Fatalln(token.Error())
	}

	publishTicker := time.NewTicker(1 * time.Second)
	defer publishTicker.Stop()

	for {
		<-publishTicker.C
		for i := 0; i < 10000; i++ {
			client.Publish("test", 0, false, "test")
		}

		log.Println("published 10000 messages")
	}
}
```
<img width="1213" alt="Screenshot 2022-12-13 at 19 14 49" src="https://user-images.githubusercontent.com/123474/207412733-227a3ee1-b3aa-4abb-94a0-7417894d8cfa.png">

**Comment by mochi-co** [comment]
Thanks @tommyminds - I was able to replicate similar issues using that code against v2.0.4. I was quite perplexed but this issue as I originally suspected it was to do with the websocket upgrader, however I reverted that back to v1.3.2 and the issue persisted.

Following this I added a bit of debugging throughout, and added a websocket listener to the `example/debug` file (you can just add the debug hook to your existing code). Unusual discovery - the malformed packet only occurs at the end of the packet issue loop, and only when the value is substantial, eg. 1000. I altered the packet send code as so:

```go
for i := 0; i < 1000; i++ {
    token := client.Publish("abc", 0, false, "tttt")
    if err := token.Error(); err != nil {
        fmt.Println(err)
    }
}
```

In order to read the packet bytes easily, I altered the topic and payload. I added prints to client ReadFixedHeader (L374) and  ReadPacket (L403) and received the following output:

```
48, 9
[0 3 97 98 99 116 116 116 116]
11:36PM DBG PUBLISH << test hook=debug m={"id":0,"payload":"tttt","qos":0,"raw":"dHR0dA==","topic":"abc"}
48, 9
[0 3 97 98 99 116 116 116 116]
11:36PM DBG PUBLISH << test hook=debug m={"id":0,"payload":"tttt","qos":0,"raw":"dHR0dA==","topic":"abc"}
48, 9
[0 3 97 98 99 116 116 116 48]
11:36PM DBG PUBLISH << test hook=debug m={"id":0,"payload":"ttt0","qos":0,"raw":"dHR0MA==","topic":"abc"}
11:36PM DBG client disconnected error="malformed packet: flags" client=test listener=ws1 remote=[::1]:55087
9 <-- 
```

the 48 is the FixedHeader Packet Type for Publish (48~3), followed by the number of remaining bytes in the packet (9). That is the packet payload: 
```
[
0 3 Topic Length
97 98 99 Topic: A B C
116 116 116 116 Payload: tttt
]
```
What you will notice is the final packet in the sequence does not have 4x `t` - it only has 3x `t`. However, because the packet header indicated there are 9 bytes remaining in the payload, the client read code continues reading the stream for all 9 bytes, which now includes the fixedheader of the next publish packet. This is survivable for the current packet, the payload is bytes afterall, but the following packet is malformed and takes on a totally different shape. The FixedHeader remaining byte has become the packet type byte, and now everything is misaligned.

The error message and behaviour is, I think, correct. It's possible there is a quirky issue in the paho clients, but it's weird that it hasn't been seen before and only happens in this scenario. It's also possible there's something unusual happening with the websocket reader in the server. I think a sensible next step would be to debug what bytes paho is sending and see if they match the issue above - both from the paho code and from an intermediary like wireshark. 

I will try to look deeper into this as soon as I can, but I have a pretty busy schedule the next few days. If you do discover anything in the meantime, please share your findings!
