### ISSUE TITLE
README.md update

### ISSUE THREAD

**Issue by BarriBarri20** [mochi-co/mqtt#137]
Hello,

I noticed that the README.md file in this repository is not up to date. The repository github.com/mochi-co/mqtt/v2 no longer exists, and there is some missing starter code on line 84.

I have a solution for this issue: we can update the README.md file to reflect the current state of the repository and include the missing starter code.

Could you please take a look at this issue and see if it can be resolved?

Thanks in advance for your help!"

I hope this helps! Let me know if you have any other questions.

**Comment by mochi-co** [comment]
Hi @BarriBarri20, can you please link to the version of the readme you are looking at? The version in master appears correct to me. 

Any references to `github.com/mochi-co/mqtt/v2` are for go import statements, which are handled by `go mod` automatically in order to correctly retrieve the latest v2.x.x version of the repo. Please review https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

**Comment by BarriBarri20** [comment]
![image](https://user-images.githubusercontent.com/72977219/211420443-b2acc147-f8be-4810-8999-24f0c165edc3.png)

Here are some of the problems Sorry, I'm not very proficient with the go language but I noticed that there are sometimes problems, could you check please?

**Comment by mochi-co** [comment]
Good catch, I hadn't noticed that was missing. Fixed in latest [v2.1.3](https://github.com/mochi-co/mqtt/releases/tag/v2.1.3) 👍🏻 

I also recommend checking out the examples folder and cmd/main.go for more ideas. I'll close this issue for now, but please feel free to ask any questions here and I will do my best to help you!

**Comment by BarriBarri20** [comment]
Thank you I appreciate it! I also fixed the mod.go thank you for your help!
