### ISSUE TITLE
onConnect and onDisconnect hooks

### ISSUE THREAD

**Issue by izarraga** [mochi-co/mqtt#16]
Hi @mochi-co

I think it would be interesting to have onConnect and onDisconnect event hooks, at least to log connections.

Igor

**Comment by mochi-co** [comment]
I agree! I have added `OnConnect` and `OnDisconnect` hooks. They have been merged and released as `v1.0.5`.

##### OnConnect
`server.Events.OnConnect` is called when a client successfully connects to the broker. The method receives the connect packet and the id and connection type for the client who connected.

```go
import "github.com/mochi-co/mqtt/server/events"

server.Events.OnMessage = func(cl events.Client, pk events.Packet) (pkx events.Packet, err error) {
    fmt.Printf("<< OnConnect client connected %s: %+v\n", cl.ID, pk)
}
```

##### OnDisconnect
`server.Events.OnDisconnect` is called when a client disconnects to the broker. If the client disconnected abnormally, the reason is indicated in the `err` error parameter.

```go
server.Events.OnDisconnect = func(cl events.Client, err error) {
    fmt.Printf("<< OnDisconnect client dicconnected %s: %v\n", cl.ID, err)
}
```
