### ISSUE TITLE
Problems with LWT

### ISSUE THREAD

**Issue by dgduncan** [mochi-co/mqtt#204]
I am having trouble getting consistent interactions with the LWT. It seems that from my testing the delayed LWT will fire; however, the hook will not always be called. I have also attempted to test with MQTTX with a locally running broker and can't get the LWT to fire at all.

I am curious if anyone else has had similar reliability issues with the LWT.

**Comment by werbenhu** [comment]
@dgduncan I have tested it and there are no issues.

Did the Will Message trigger under any of these conditions?

The Will Message must be published when the network connection is subsequently closed unless the Server deletes the Will Message upon receipt of a DISCONNECT Packet [MQTT-3.1.2-8].

Situations in which the Will Message may be published include, but are not limited to:

An I/O error or network failure detected by the Server.
The Client fails to communicate within the Keep Alive time.
The Client closes the Network Connection without first sending a DISCONNECT Packet.
The Server closes the Network Connection because of a protocol error.

It's possible that you closed the MQTT connection normally, so you didn't receive the LWT. You could try disconnecting the client by directly closing the MQTTX client software, causing a network abnormality, to see if the Will Message is triggered.

**Comment by mochi-co** [comment]
@dgduncan If you can provide a pattern for reproducing this issue I can look into it 👍🏻

**Comment by dgduncan** [comment]
@mochi-co @werbenhu I am going to close this issue. I need to do a more further investigation. In a whirlwind of a night I attempted to move everything I used over to MQTT V5 without doing a full investigation.

**Comment by mochi-co** [comment]
@dgduncan best of luck!
