### ISSUE TITLE
Default server keep alive setting overrides the client keep alive value

### ISSUE THREAD

**Issue by brutella** [mochi-co/mqtt#208]
If a client uses protocol version 3.1.1 and connects with a keep alive value of `0`, the server ignores it and assigns the server keep alive (default is `10s`). See https://github.com/mochi-co/mqtt/blob/d46e7b5bcfbeca238f62f5076e2bc7f95592fe9d/clients.go#LL215C34-L215C34

This results in a disconnect after 15 seconds (10 seconds * 1.5).

Shouldn't there be a check for the protocol version, before overriding the client specified keep alive value? 

```go
if pk.ProtocolVersion > 4 { // higher than v3.1.1
    cl.State.keepalive = cl.ops.options.Capabilities.ServerKeepAlive
}
```

Otherwise the client doesn't now, that the server sets a deadline for that connection.

**Comment by thedevop** [comment]
The server does normally honor the client keepalive value:
https://github.com/mochi-co/mqtt/blob/d46e7b5bcfbeca238f62f5076e2bc7f95592fe9d/clients.go#L215-L218

It first set a default value, then reset it to Keepalive value in CONNECT if it's > 0.

@mochi-co , given 0 is valid (turn off keepalive), perhaps the keepalive should just always be set to the keepalive value in CONNECT?

**Comment by mochi-co** [comment]
I couldn't remove this entirely as the paho tests expect server keep alive to be settable in order to pass. 

However, I've removed the Capabilities.ServerKeepAlive parameter and refactored the client state to provide a new ServerKeepalive flag. All clients now use their specified keep alive (0, or non-0), and the Server Keepalive (and ServerKeepalive flag) can be set using the OnConnect hook, for example:

```go

func (h *pahoAuthHook) OnConnect(cl *mqtt.Client, pk packets.Packet) {
	// Handle paho test_server_keep_alive
	if pk.Connect.Keepalive == 120 && pk.Connect.Clean {
		cl.State.Keepalive = 60
		cl.State.ServerKeepalive = true
	}
}
```

This will ensure the Connack contains the required ServerKeepalive property, as set.

Let me know if it works (or not)!

**Comment by brutella** [comment]
Thanks for the fix. It works now. 🎉
