### ISSUE TITLE
Adding more performance benchmarks

### ISSUE THREAD

**Issue by IshanDaga** [mochi-co/mqtt#224]
Hi @mochi-co !

Have been using this broker in production (single node for now) for the last three months now, thanks for the great work !
Internally we were wondering if we should switch to a Rust-based embedded broker, something like https://github.com/bytebeamio/rumqtt - would it be too much of a hassle for you to include the benchmarks for this as well on your environment ?

Thanks !

**Comment by mochi-co** [comment]
Hi @IshanDaga! Sorry for the delay, I will try to get this added as soon as I can.

**Comment by mochi-co** [comment]
@IshanDaga I've added the latest benchmarks to README.md:

`mqtt-stresser -broker tcp://localhost:1883 -num-clients=2 -num-messages=10000`
| Broker            | publish fastest | median | slowest | receive fastest | median | slowest | 
| --                | --             | --   | --   | --             | --   | --   |
| Mochi v2.2.10      | 124,772 | 125,456 | 124,614 | 314,461 | 313,186 | 311,910 |
| [Mosquitto v2.0.15](https://github.com/eclipse/mosquitto) | 155,920 | 155,919 | 155,918 | 185,485 | 185,097 | 184,709 |
| [EMQX v5.0.11](https://github.com/emqx/emqx)      | 156,945 | 156,257 | 155,568 | 17,918 | 17,783 | 17,649 |
| [Rumqtt v0.21.0](https://github.com/bytebeamio/rumqtt) | 112,208 | 108,480 | 104,753 | 135,784 | 126,446 | 117,108 |

`mqtt-stresser -broker tcp://localhost:1883 -num-clients=10 -num-messages=10000`
| Broker            | publish fastest | median | slowest | receive fastest | median | slowest | 
| --                | --             | --   | --   | --             | --   | --   |
| Mochi v2.2.10      | 41,825 | 31,663| 23,008 | 144,058 | 65,903 | 37,618 |
| Mosquitto v2.0.15 | 42,729 | 38,633 | 29,879 | 23,241 | 19,714 | 18,806 |
| EMQX v5.0.11      | 21,553 | 17,418 | 14,356 | 4,257 | 3,980 | 3,756 |
| Rumqtt v0.21.0    | 42,213 | 23,153 | 20,814 | 49,465 | 36,626 | 19,283 |

Million Message Challenge (hit the server with 1 million messages immediately):

`mqtt-stresser -broker tcp://localhost:1883 -num-clients=100 -num-messages=10000`
| Broker            | publish fastest | median | slowest | receive fastest | median | slowest | 
| --                | --             | --   | --   | --             | --   | --   |
| Mochi v2.2.10     | 13,532 | 4,425 | 2,344 | 52,120 | 7,274 | 2,701 |
| Mosquitto v2.0.15 | 3,826 | 3,395 | 3,032 | 1,200 | 1,150 | 1,118 |
| EMQX v5.0.11      | 4,086 | 2,432 | 2,274 | 434 | 333 | 311 |
| Rumqtt v0.21.0    | 78,972 | 5,047 | 3,804 | 4,286 | 3,249 | 2,027 |

**Comment by torntrousers** [comment]
Could you give some analysis context comments around that?  Are higher or lower numbers better? Mochi has a much bigger numer in the slowest column, and a much bigger number in the publish fastest column too - is that good or bad?

**Comment by mochi-co** [comment]
@torntrousers For sure! Generally speaking, the numbers give a sense for the concurrent message throughput of the broker.  

There's two main things I would note. First is, as I noted on the readme:
> The values presented in the benchmark are not representative of true messages per second throughput. They rely on an unusual calculation by mqtt-stresser, but are usable as they are consistent across all brokers. 

While mqtt-stresser reports these as messages per second, it's a bit of an unusual score as it's based on a histogram, which reports the number of messages per second per percentage of all messages (you can see the code here: https://github.com/inovex/mqtt-stresser/blob/master/report.go). Because many mqtt benchmarks were previously run over a longer period of time with lower message counts, my suspicion (I haven't looked too deeply into the code) is that the comparison unit calculation is wrong. 

Out of interest, I added a `start := time.Now()` and `fmt.Println(time.Since(start).Milliseconds(), "ms")` around the `finEvents` loop in the mqtt-stresser main.go and ran it with `-num-clients=10 -num-messages=10000`. On battery, it completed in a little under 650ms, but it reports as `Fastest: 25958 msg/sec` despite having transmitted 200,000 messages in a little over half a second. I am considering forking it and trying to implement a more 'intuitive' report number.

In any event, the values are consistent across all runs and brokers, so it still serves for benchmarking purposes (if not capacity planning). For all brokers the variation between runs is never more than about 5%.

Higher numbers are better - you want to have more messages processed per second (or millisecond), but fastest is not necessarily a useful number unless you are expecting intermittent burst traffic. However, see the histogram generated by mqtt-stresser below:

```
-num-clients=100 -num-messages=10000
# Receiving Througput
Fastest: 16965 msg/sec
Slowest: 2308 msg/sec
Median: 4847 msg/sec

  < 3774 msg/sec  24%
  < 5239 msg/sec  57%
  < 6705 msg/sec  77%
  < 8171 msg/sec  87%
  < 9637 msg/sec  92%
  < 11102 msg/sec  93%
  < 12568 msg/sec  97%
  < 14034 msg/sec  98%
  < 15500 msg/sec  99%
  < 18431 msg/sec  100%
```
As the quantity of messages increased, you can't always rely on fastest to be consistent. At 1 million messages (on this laptop, battery power), the capacity of the broker to keep up with the throughput is quickly saturated. In fact, only ~8% of the messages sent were processed fastest enough to be considered above 10k/s, while at least half of them were only a third of the "fastest" reported speed. Fastest allows us to see the upper limit of the broker processing speed, before saturation.

Slowest, on the other hand, is a good indicator of how the broker will perform when saturated. As noted, the actual number itself is meaningless in terms of actual capacity planning, but if you take it as a relative value you can get a sense for how a broker performs compared with its peers.

Median is probably the best overall metric for typical minute-to-minute performance, neither saturated nor empty, and we can usually find that all the brokers tend to operate within a fairly narrow range of each other.

In real terms, all the brokers are going to be more than sufficiently performant for most people's usage - really the only point of differentiation is the implementation and feature-set provided by each.

Not sure if that helps clarify the numbers at all, but let me know if you have any thoughts or questions!

**Comment by torntrousers** [comment]
Really helpful, thanks!

**Comment by IshanDaga** [comment]
Awesome ! Thanks @mochi-co ! Closing this as completed :)
