### ISSUE TITLE
How can i connect to WS listener?

### ISSUE THREAD

**Issue by JackCloudman** [mochi-co/mqtt#5]
Hello, I'm trying to use this example by eclipse,
https://www.eclipse.org/paho/index.php?page=clients/js/index.php
but, when I try to connect to ws server I get this error: 
![image](https://user-images.githubusercontent.com/17970185/139745786-427948d2-2379-498c-85f6-472ab8aa23c3.png)
I'm using this example: https://github.com/mochi-co/mqtt/blob/master/examples/websocket/main.go

Thanks :c

**Comment by mochi-co** [comment]
Hi @JackCloudman! 

Try connecting to the address`ws://localhost:1882` without the `/mqtt` path. Currently the broker listens for websocket connections on the root path (`/`). Let me know if this helps.

**Comment by JackCloudman** [comment]
I got same error :( 
![image](https://user-images.githubusercontent.com/17970185/139756615-dccc0f77-87af-4dd4-a465-7ec1639b8cee.png)

**Comment by mochi-co** [comment]
@JackCloudman Have you tried connecting using an MQTT client? Does it connect or does it return the same error? Also try connecting to `127.0.0.1` and see what that does.

**Comment by JackCloudman** [comment]
No, doesn't work, the error is the same, I can't connect to ws://localhost:1882 or ws://127.0.0.1:1882, and I tried changing the port but doest not work.

**Comment by mochi-co** [comment]
That's unusual... Can you confirm the example is running eg. how are you starting the example - what does is the output?

**Comment by ClarkQAQ** [comment]
> 您好，我正在尝试通过 Eclipse 使用此示例， [https:](https://www.eclipse.org/paho/index.php?page=clients/js/index.php) //www.eclipse.org/paho/index.php?page=clients/js/ index.php 但是，当我尝试连接到 ws 服务器时，我得到了这个错误： 我正在使用这个例子：[https ://github.com/mochi-co/mqtt/blob/master/examples/websocket/main.go](https://github.com/mochi-co/mqtt/blob/master/examples/websocket/main.go) ![图片](https://user-images.githubusercontent.com/17970185/139745786-427948d2-2379-498c-85f6-472ab8aa23c3.png)[](https://github.com/mochi-co/mqtt/blob/master/examples/websocket/main.go)
> 
> 谢谢：c

I used to be like this too, now the issues should be fixed
see url: https://github.com/mochi-co/mqtt/commit/b9db59ba121d4fe8ea24babe9fc9cf581f0a51be

**Comment by Surgbc** [comment]
The clients I am using use `mqttv3.1` protocol. So the  software does not work at it is with `Subprotocols: []string{"mqtt"},` as given [in this PR](https://github.com/mochi-co/mqtt/commit/b9db59ba121d4fe8ea24babe9fc9cf581f0a51be#diff-ccf9d93e82328eb01cdabfe3f36bc9f3204b28665ebe140619a077365f57f67f). I have had to modify it to:

```
wsUpgrader = &websocket.Upgrader{
		Subprotocols: []string{"mqtt", "mqttv3.1"},
		CheckOrigin: func(r *http.Request) bool {
			return true
		},
	}
```

This [hivemq test page](http://www.hivemq.com/demos/websocket-client/) and the npm mqtt library both use, for now `mqttv3.1`

It would be great if the subprotocol could be automatically read from the client request header.

I have noticed that no library that uses which uses [gorilla/websocket] works due to this. I do not know how [golang.org/x/net/websocket] does the handshake, but it works well.
