### ISSUE TITLE
Unable to publish messages with larger payload sizes

### ISSUE THREAD

**Issue by deadprogram** [mochi-co/mqtt#54]
I was testing out the 1.2.0 branch of this broker, and discovered that it appears to fail silently when i try to publish messages with a larger-sized (>100k) binary payload.

Any thoughts? Thanks in advance.

**Comment by jmacd** [comment]
(I wonder what happens if a single request exceeds the size of the circular buffer.)

**Comment by mochi-co** [comment]
> (I wonder what happens if a single request exceeds the size of the circular buffer.)

The default buffer size is `1024 * 256` (262,144 bytes). There is capacity in `EstablishConnection` to set this value (currently hardcoded `0` to use default), but it hasn't been opened to allow a custom value as yet.

https://github.com/mochi-co/mqtt/blob/0a7205e1104c323560d66bea8b8a83b38b31c19d/server/server.go#L180-L190

@deadprogram I would be interested to know what happens if you increase the size of the following values:

https://github.com/mochi-co/mqtt/blob/0a7205e1104c323560d66bea8b8a83b38b31c19d/server/internal/circ/buffer.go#L11-L15

If increasing the buffer size allows it to successfully work, we should implement a parameter to adjust this value, and potentially increase the default size.

**Comment by deadprogram** [comment]
Thanks for the quick response. I just tried increasing both of those values, and it did indeed resolve that problem. 

From a brief reading of the code seems like `server.New()` is where the buffer size needs to be able to be changed from the default value.

So what is the best way to proceed from here?

**Comment by mochi-co** [comment]
I think the next step should be adding parameters to server allowing the operator to modify the buffer sizes. I'll try to get a PR done for this in the coming week and we can add it to v1.2.0.
