### ISSUE TITLE
Authentication/Acl with http 

### ISSUE THREAD

**Issue by amanasmuei** [mochi-co/mqtt#64]
Hi,
How can i do authentication for each MQTT client to the user's own web server / web service ?
Thanks

**Comment by mochi-co** [comment]
Hi @amanasmuei - Can you provide some more information about your use case? That will help us advise you better.
Thanks!

**Comment by amanasmuei** [comment]
Hi @mochi-co,

Herewith is the attached image as for details info.

<img width="706" alt="Screenshot 2022-04-13 at 4 04 41 PM" src="https://user-images.githubusercontent.com/25909625/163129894-c66748ed-fd6b-40d6-b1b1-01d8967963a4.png">

Thanks!

**Comment by mochi-co** [comment]
I noticed that there was no example file for using [the `auth.Controller` interface ](https://github.com/mochi-co/mqtt/blob/master/server/listeners/auth/auth.go), so I have added one in [examples/auth/main.go](https://github.com/mochi-co/mqtt/blob/master/examples/auth/main.go)

Generally speaking, you would create a struct which has the `ACL(user []byte, topic string, write bool) bool` and `Authenticate(user, password []byte) bool` methods so that it fulfils the `auth.Controller` interface signature. `Authenticate` would then check the username and password against whatever you are using to validate your rest API.

Let me know if that helps or if you need further information! :)

**Comment by amanasmuei** [comment]
TQvm
